### ISSUE TITLE
indentation suggests drunk hackers over there!!

### ISSUE THREAD

**Issue by giuscri** [aroblu94/aro94-s-blog#1]
https://raw.githubusercontent.com/aroblu94/aro94-s-blog/master/js/script.js
:beers:
:))))

**Comment by aronnebrivio** [comment]
Ma sai che credo che abbia fatto tutto github? Io sul mio pc lo vedo tutto ok bo... Comunque sistemerò :)

**Comment by giuscri** [comment]
`less`a il file. Lui non mente. Probabilmente l'editor fa qualcosa di strano. Ciao :)

**Comment by aronnebrivio** [comment]
Ti farò sapere se ho un editor MENTIROSO, ciao!! :)
