### ISSUE TITLE
Impossibile tornare indietro dalle immagini a schermo pieno

### ISSUE THREAD

**Issue by airon90** [aroblu94/aro94-s-blog#4]
Quando si fa doppio tap sulle immagini, esse si ingrandiscono a schermo pieno. Tuttavia, usando Flame, che non ha un bottone "Indietro" risulta impossibile tornare indietro nel testo dell'articolo e quindi bisogna riavviare l'app

**Comment by aronnebrivio** [comment]
Hai ragione, vedrò di risolvere al più presto, grazie per la segnalazione!!
